string month5 = MapDemo.retreiveMonth(5);
system.debug('month 5 : ' + month5);

string month10 = MapDemo.retreiveMonth(10);
system.debug('month 10 : ' + month10);

string month15 = MapDemo.retreiveMonth(15);
system.debug('month 15 : ' + month15);

system.debug('month 9: ' + MapDemo.retreiveMonth(9));
//MapDemo.mapItemPrices();
//MapDemo.map1ForEach();

packaging/installPackage.apexp?p0=04tDo000000HsDd


https://login.salesforce.com/packaging/installPackage.apexp?p0=04tDo000000HsDx